# Generated by Django 5.1.6 on 2025-02-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('pending', 'Pending'), ('done', 'Done'), ('доставлен', 'Delivered')], default='pending', max_length=10),
        ),
    ]
