# Generated by Django 5.1.6 on 2025-02-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_category_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('dine_in', 'В зале'), ('takeaway', 'На вынос'), ('delivery', 'Доставка')], default='dine_in', max_length=10, null=True),
        ),
    ]
