# Generated by Django 5.1.6 on 2025-04-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_total_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_sum',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
