# Generated by Django 5.1.6 on 2025-04-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Наличный'), ('online', 'Перевод')], default='cash', max_length=15, verbose_name='Оплата'),
        ),
    ]
