# Generated by Django 5.1.6 on 2025-06-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Наличный'), ('online', 'Перевод'), ('free', 'Бесплатно')], default='cash', max_length=15, verbose_name='Оплата'),
        ),
    ]
