# Generated by Django 5.1.6 on 2025-05-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
