# Generated by Django 5.1.6 on 2025-08-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Отменен'), ('pending', 'В ожидании'), ('done', 'Готов'), ('delivered', 'Выполнен')], default='pending', max_length=10, verbose_name='Статус'),
        ),
    ]
