# Generated by Django 5.1.6 on 2025-09-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_table',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Стол №'),
        ),
    ]
