# Generated by Django 5.1.6 on 2025-09-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
