# Generated by Django 5.1.6 on 2025-09-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_order_order_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_table',
        ),
    ]
