# Generated by Django 5.1.6 on 2025-09-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_order_table_number'),
        ('orders', '0024_remove_order_order_table'),
    ]

    operations = [
    ]
