# Generated by Django 5.1.6 on 2025-09-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_order_completed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completed_at',
        ),
        migrations.AddField(
            model_name='order',
            name='order_completion_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время выполнения заказа'),
        ),
    ]
