# Generated by Django 5.1.6 on 2025-09-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_remove_order_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_completion_time',
        ),
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время завершения'),
        ),
    ]
