# Generated by Django 5.1.6 on 2025-09-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_remove_order_order_completion_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('', 'Тип оплаты не выбран'), ('cash', 'Наличный'), ('online', 'Перевод'), ('free', 'Бесплатно')], default='', max_length=15, verbose_name='Оплата'),
        ),
    ]
