# Generated by Django 5.1.6 on 2026-07-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_alter_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Отменен'), ('pending', 'Принят'), ('done', 'Готов к выдаче'), ('delivered', 'Выдан')], default='pending', max_length=10, verbose_name='Статус'),
        ),
    ]
