# Generated by Django 5.1.6 on 2025-11-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_alter_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, help_text='Дополнительная информация к заказу', max_length=500, null=True, verbose_name='Комментарий к заказу'),
        ),
    ]
