# Generated by Django 5.1.6 on 2026-07-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Сумма наличными'),
        ),
        migrations.AddField(
            model_name='order',
            name='online_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Сумма переводом'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Наличный'), ('online', 'Перевод'), ('mixed', 'Смешанный'), ('free', 'Бесплатно')], default='cash', max_length=15, verbose_name='Оплата'),
        ),
    ]
