# Generated by Django 5.1.6 on 2025-11-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Сумма наличными'),
        ),
        migrations.AddField(
            model_name='order',
            name='online_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Сумма переводом'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Наличный'), ('online', 'Перевод'), ('mixed', 'Смешанный'), ('free', 'Бесплатно')], default='cash', max_length=15, verbose_name='Оплата'),
        ),
    ]
