# Generated by Django 5.1.6 on 2025-11-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_order_cash_amount_order_online_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cash_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма наличными'),
        ),
        migrations.AlterField(
            model_name='order',
            name='online_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма переводом'),
        ),
    ]
