# Generated by Django 5.1.6 on 2025-11-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_alter_order_cash_amount_alter_order_online_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cash_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=10, null=True, verbose_name='Сумма наличными'),
        ),
        migrations.AlterField(
            model_name='order',
            name='online_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=10, null=True, verbose_name='Сумма переводом'),
        ),
    ]
