# Generated by Django 5.1.6 on 2025-11-16 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_alter_order_cash_amount_alter_order_online_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='orders.category', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер стола'),
        ),
    ]
